### ISSUE TITLE
Enabling/disabling of service items

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#137]
In #60, I stated some reasons why `svc_systemd` does not support `enable` or `disable`. I'm not so sure about that anymore.

Given BundleWrap's mindset and its current feature set (canned actions!), I think that we should provide a way to simply enable or disable a service. If the user wants fancy stuff, he can still create symlinks by himself.

(This is less relevant for Debian based systems because most daemons are activated by default here. On Arch, though, you'll end up with a lot of manually defined symlinks.)

**Comment by trehn** [comment]
Closing this, open new issues for individual items if you want.
