### ISSUE TITLE
file item: verify_with

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#139]
`files = {"/etc/sudoers": {'verify_with': "visudo -c -f {}"}}`

visudo has to exist and behave the same on both the node (for `bw verify`) and locally (for everything else). Other use cases: xmllint, bash -n, pylint, ...

**Comment by trehn** [comment]
@vain care to weigh in?

I'm leaning towards always running the verify_with command locally and never on the node. verify_with is an additional safety for generating files. `bw verify` is not special. It has to render files just as `bw apply` has to and part of the rendering process is running the verify command.

**Comment by vain** [comment]
As a regular user, I’d expect `verify_with` to run on the node.

If `verify_with` runs locally, a) the verification tool has to exist locally (which can be annoying if it’s part of a huge package), b) the verification tool has to behave exactly the same as the one on the node (which, I guess, can be a problem – just think of patches of redhat or ubuntu).

`bw test` is a big problem, though. If `verify_with` runs on the node, what does `bw test` do? No verification at all? That’s bad. Does it do local verification where the local tool might come up with different results than the one on the node … ?

Either way, you get inconsistent behaviour:

* Run it locally and things can break as soon as they’re applied on the node.
* Run it on the node and `bw test` (people might blindly trust `bw test`) might not be able to catch errors, thus things can break on the node, i.e. a `bw apply` will fail.

I don’t think `verify_with` can be implemented in a clean way. :/ If anything, it should run on the node (to safe the user from the hazzle mentioned above and to create the most meaningful results by using “native” tools on the node) and it should be marked as an additional, weak safety net which you should not trust blindly.

**Comment by trehn** [comment]
Definitely not an easy choice. How about this:

* ``verify_with`` runs on the node where we can control the environment and ensure consistency
* ``bw test`` runs the ``verify_with`` command locally unless called with ``--no-verify-with``

My guess is that running locally will work fine in 90% of cases. If your nodes have a patched visudo or different bash version, you can just remove the verification step and still have the error get caught when you apply.

**Comment by trehn** [comment]
Damn, this is tricky to get right. I just implemented it this way:

>``verify_cmd_local`` and ``verify_cmd_remote``

>These attributes can be used to run external validation commands on a file before it is applied to a node. The file is first written to a temporary location, verified there and moved into place only if verification succeeds. Verification is considered successful when the exit code of the verification command is 0. Use ``{}`` as a placeholder for the shell-quoted path to the temporary file. Here is an example for verifying sudoers files:
>
>	visudo -cf {}
>
>Note that as the name suggests ``verify_cmd_local`` is executed on the machine running BundleWrap while ``verify_cmd_remote`` is executed on the node. In many cases, you can use the exact same command for both attributes. Sometimes however a command can only be made available locally or on the node. In this case you obviously only set the corresponding attribute. Setting both commands (as opposed to only the remote one, which will usually be more important) allows ``bw test`` to still perform verification without touching the network. During ``bw apply`` and ``bw verify``, only the remote command will be used if both are set.

This is not great either because it violates an unwritten rule of BundleWrap: anything it can detect, it can fix. What are we to do if the verify command on a node fails? Raising an exception is too extreme, since only one item is affected. We can't just fail get_status() either, because then what do we ask()? We're looking at an issue bw cannot fix, something that has been carefully avoided so far in all items.

So if no one comes up with a better idea like right now, I'm going to implement this as I suggested on Jan 5th:

>I'm leaning towards always running the verify_with command locally and never on the node. verify_with is an additional safety for generating files. bw verify is not special. It has to render files just as bw apply has to and part of the rendering process is running the verify command.

That's pretty much the only solution that avoids the "unfixable" issue because we can just raise the validation error like we do template syntax errors. It's not a perfect solution, but I think it's the best we can offer.
