### ISSUE TITLE
setgid directories are not directories?

### ISSUE THREAD

**Issue by bkendinibilir** [bundlewrap/bundlewrap#171]
╭  directory:/var/www/xxxxxxxxxxxxxxx.de
 ┃
 ┃   Not a directory. The `file` utility says it's a 'setgid directory'.
 ┃   Do you want it removed and replaced?
 ┃
 ╰  Fix directory:/var/www/xxxxxxxxxxxxxxx.de? [Y/n] n

> ls -lad /var/www/xxxxxxxxxxxxxxx.de
drwxrwsr-x 3 root website 4096 May 11 19:08 /var/www/xxxxxxxxxxxxxxx.de

The directory mode is set to "0277" in bw bundle.

bug?

**Comment by trehn** [comment]
Yup, that's a bug.

**Comment by bkendinibilir** [comment]
That was quick, thx!

Is a hotfix-release v1.5.1 planned?

Till then, I use:

git clone https://github.com/bundlewrap/bundlewrap.git
cd bundlewrap
git checkout tags/1.5.0
git cherry-pick 32ea4a1
sudo python setup.py develop

**Comment by trehn** [comment]
A bugfix release is not planned since this is the only bug I'm aware of atm.

**Comment by trehn** [comment]
btw, I recommend `pip install -e .` over `python setup.py develop` (which is like using easy_install)

**Comment by bkendinibilir** [comment]
Ok.

`python setup.py develop` comes from http://docs.bundlewrap.org/en/1.5.0/installation.html#from-git
