### ISSUE TITLE
hooks for `bw test`

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#172]
Allow users to define additional validations to be run during `bw test`.

**Comment by bkendinibilir** [comment]
Can you please add also "bw verify" and "bw items"?
I want to change globally node metadata to import secrets from teamvault, but actually I can only hook on "bw apply" and "bw run".

My workaround is, that I execute the code/change the metadata in a bundle, which is assigned to all nodes via groups pattern as first bundle *ughs* ;-)

**Comment by trehn** [comment]
That doesn't sound like a job for a hook. You'd have to add the same logic to ALL commands.

I don't really understand the problem, but maybe you're looking for metadata processors? http://docs.bundlewrap.org/en/1.5.1/groups.py.html#metadata-processors
What metadata are you changing and why?

**Comment by bkendinibilir** [comment]
Yeah, I had actually been looking for this, perfect! :)
