### ISSUE TITLE
config hashes for nodes and groups

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#181]
Sometimes I make sweeping changes to a repo, but want to make sure they don't affect certain nodes or groups. If we could compute a hash for the entire config of a node (and then a hash combining all nodes in a group), I could verify that this node/group really hasn't changed.

**Comment by trehn** [comment]
This would obviously even more useful if there was a way to diff two entire configs. But I don't believe that we'll get good results by just dumping a serialization into two text files and running `diff -u`.

**Comment by vain** [comment]
By "sweeping changes" you mean changes like removing/refactoring a bundle and you want to make sure that all stuff *except for that bundle* remains identical, right? You want to make sure that there are no unexpected side effects?

So, this is not about refactoring the code of a bundle and checking whether the new code produces the same results.

I think: Drop the idea of creating hashes. Instead, extend `bw items -w ...`. This is already a very helpful tool, but it currently does not render/write/produce everything. It only does half the job. So, include all item types and all information. Stuff like packages or users could be written to dotfiles -- or put everything into a single dotfile. The user can then use the common `diff -Naur` to see what has been changed.

**Comment by trehn** [comment]
I don't think `bw items -w` can do what I want here. 

I want to be able to write another tool on top of bw for this: "here's two git refs, show me all nodes that are affected by the changes between these refs". 

To write the entire configuration to disk locally would still require us to come up with a serialization (hey, JSON) for non-file items. So we're doing that anyway. But not even file and directory items can be fully represented here, since I can't make local files have the owner and group they should have on the node. So I'd have to create sidecar files to each managed file... nope.

Implementing a generic way to represent a configured item as JSON would also allow us to provide a default implementation of `Item.ask()` and open up some possibilites for improving `bw apply` output (see #164).

Being able to compute a hash for the entire repo, each group, each node, and each item will probably yield a lot of future benefits, too. For example, we could leave the current node hash on the node after an apply and then have a "quick apply" mode that will skip the node if the hash on the node matches the current hash (removing the need to check each item if you're confident that only bw is making changes to your nodes).

**Comment by trehn** [comment]
So let's say items build a default state dict from their attributes as provided by the user. We run that through `patch_attributes` like we do now and save it on the item. A copy of this dict is then fed into a new method that transforms this dict into a dict that describes the state of the item on the node. The default implementation of the latter method just returns the unaltered first dict.

Why two dicts? Consider large binary files. We do not want to read the entire file into memory, thus we store only a hash of the file contents in the second dict. However, we do need to keep track of where the source file is located in our repo, so that information goes into the first dict. Note that merely renaming the source file in the repo (without changing the target filename on the node) should not change the hash for this item.

The problem with this system is that correctness is a matter of implementation, not design. It's very possible for us to screw up and put something in the first dict (which will be used to modify the node), but not the second (which is responsible for the hash). But we cannot rely on the second dict alone to make changes because of the local path problem explained above.

**Comment by trehn** [comment]
`Item.get_status()` also produces a state dict (the second kind mentioned above).

The state dict would have certain restrictions:

* keys must be strings
* values can be simple types:
 * string
 * int
 * float
 * decimal
 * bool
* ...or lists/tuples containing only the simple types listed above

This enforces flatness and simplicity and prevents people from building overly complex items. It also provides a clearly defined scope for us to implement a diff operation on two of these dicts and present the result to the user, obsoleting `Item.ask`.

An empty state dict indicates that an item should be deleted or does not yet exist.

**Comment by trehn** [comment]
CLI:

```
bw hash mynode:file:/etc/hostname
```

Prints the hash for this file.

```
bw hash mynode
```

Prints a hash of the hashes of all items on that node.

```
bw hash mygroup
```

Prints a hash of all hashes of all nodes in that group.

```
bw hash
```

Prints a hash of all hashes of all nodes.
