### ISSUE TITLE
`bw lock` to manually lock nodes

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#191]
`-u` to unlock

`-m` for optional message

**Comment by vain** [comment]
How about a "special" kind of lock which can not be overriden by *other* users (via bw -- of course, the user can always manually remove /tmp/bundlewrap.lock)? I myself want to be able to work on the node, but I want to prevent others from interfering.

**Comment by trehn** [comment]
Hm, but how do we tell different users apart? The local username currently in the lock file is fragile, the remote user on the node might be shared.

**Comment by trehn** [comment]
This probably has to be entirely separate from the existing locking system (which also prevents multiple applies from the same user).

**Comment by vain** [comment]
Why do you consider the local username fragile?

I can only think of one scenario: A user works on multiple workstations, each with a different username. Frankly, I don’t think that’s very common.

**Comment by trehn** [comment]
I was more concerned about two persons using the same username on their respective machines ("admin", "ubuntu", ...).

But I guess #194 is sufficient to address this.

**Comment by vain** [comment]
Arrrr. People who do this simply deserve to override/ignore each other’s lock files.

**Comment by trehn** [comment]
Locks should also have a default timeout of 8h.

Keep in mind that we can't break backwards compatibility with existing lock files (since people using the same repo might be on slightly different versions of bw). Therefore, the current lock file format has to stay. I'm undecided whether we should add a default timeout for these existing locks.

Now the problem is that adding a second lock file to the same directory will break all prior versions (they find a lock dir without the file they're looking for). So we have to add a second lock directory. This new kind of lock is of course unknown to and ignored by prior versions of bw.

I propose these new lock file contents:

```json
[
{
    "date_acquired": 1234567890,
    "date_timeout": 9876543210,
    "locked_by": "jdoe@example.com",
    "exempt_from_lock": ["jdoe@example.com"],
    "block": ["apply", "lock"]
}
]
```

Note that it's a list, so we can add additional locks that overlap on a node. This is important so more than one person can place a lock on a node. Why is that a thing? Because with `block` we can specify which actions we want to block: "apply" obviously blocks `bw apply`, while "run" blocks `bw run` and "lock" prevents anybody from placing additional locks on the node. This makes it possible for independent users to disable applying configuration and exempt the nodes from large scale `bw run`s.

CLI:

```
$ bw lock --unlock NODE|GROUP  # removes all locks from node owner by current user
$ bw lock --unlock --force NODE|GROUP  # removes all locks from node (even from other users)
$ bw lock --block apply,lock,run --timeout 8h NODE|GROUP  # --block defaults to "apply" only
$ bw lock --dont-exempt-me NODE|GROUP
```

I don't think we need to enable further customization of `exempt_from_lock` on the command line. It defaults to the current user.

**Comment by vain** [comment]
Yeah, that's just about perfect. :)

I don't like the idea of two different locking mechanisms, but I get that it shouldn't break previous versions. We should remember to merge those locks in bw 3.0.

**Comment by trehn** [comment]
OK, different idea:

Keep the locking mechanism as it is. Additionally, there is a new directory called `/tmp/bw.locks/` or something.

In that dir, multiple files may exist. They have random 8-character names like `deadbeef`.

Each file contains exactly one line. The line is formatted something like this:

`<filename>:restrict_apply_to:<BW_IDENTITY>:<timestamp>`

In `bw apply` we can then simply `cat /tmp/bw.locks/*` to get an aggregate view of all special locks. If there are none, we can just proceed with the apply as before. If a `restrict_apply_to` lock is found, we have to check if our own `BW_IDENTITY` part of any `restrict_apply_to` lock. If it is, we go ahead and lock the node as before. It it isn't, we deny the apply.

It would be trivial to add another expiry timestamp that limits the lifetime of the lock. Locks can easily be removed by deleting their respective file.

This way we avoid the need to lock a single file that contains multiple locks. We can safely get a consistent view of all locks. We can also add and remove locks without risking race conditions in a download-modify-upload pattern.
