### ISSUE TITLE
support for BSD

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#192]
It seems that with bw 2.0, the only thing that prevents us from supporting (Open)BSD is `sha1` and `stat`.

I'd rather avoid introducing configuration telling nodes whether they're BSD or Linux. We may be able to get away with just running:

`sha1sum -- /file || sha1 -q -- /file`

and a similar `stat` command.

**Comment by timbuchwaldt** [comment]
Fuck yeah! :) take my money!

**Comment by vain** [comment]
Just for the record: There is no `useradd` or `usermod` in FreeBSD.

Instead, both are subcommands of `pw`, i.e. you’d do `pw useradd foobar -m`. Also note that order matters, so a GNU-like `pw useradd -m foobar` does not work.

**Comment by trehn** [comment]
192131dedd5fbb553551d77eae01dd152f4a2a39 introduces an "os" attribute for nodes and groups so we don't need to mess around with `||`

I'm not sure yet if or when or how to begin "formal support" of non-Linux platforms, but it kind of works now...

**Comment by trehn** [comment]
With http://marc.info/?l=openbsd-ports&m=146758466818788&w=2 it's probably time to think a little bit more about how we're going to tackle support and abstraction of different OSes and Linux distributions.

We started down a very pragmatic and flat path with the different pkg_* and svc_* items. We strayed from that in a way by introducing `node.os`, which is only used to make BundleWrap smarter and automatically adjust its behavior for the different major OSes.

People coming from other config management system often find it strange to explicitly select a package manager instead of letting BundleWrap work that out on its own.

A shallow way of dealing with this is to introduce a pre-processing step to bundles that turns

```
packages = {'foo': {}}
```

into

```
pkg_apt = {'foo': {}}
```

or

```
pkg_yum = {'foo': {}}
```

internally, depending on `node.os` and probably also a new `node.os_flavor` and `node.os_version`. It would have to raise an error if one of these variables was undefined. The upside is that it's backwards compatible. Still, there would be two ways we're dealing with OS differences: small stuff like command line options are programmed into a single item while larger differences like init systems or package managers require entirely separate items with the aforementioned pre-processor as an abstraction layer.

Random other thoughts:
* Ubuntu uses different init systems alongside each other, though they provide their own abstractions. But that will probably evolve in future versions.
* BSDs can have `sudo` or `doas` (#261) and there are even more options in Solaris/Sun country
* the pre-processor can only work with builtin items, unless we come up with a way for custom items to provide logic to "claim" certain abstract attributes like `services` and `packages` - which will easily get complicated and over-engineered

I'll sleep on it some more.

**Comment by trehn** [comment]
The pre-processor in my mind just got a little more complex, since we need to make this an error:

```
packages = {'foo': {}}
files = {'/foo': {'needs': ['pkg_apt:foo']}}
```

A simple mapping would make this an error on CentOS, but not on Debian. That's bad. So we need to check all `needs` and `triggers` for item IDs that would be created by a pre-processor (and raise an error if any are found) and *then* we'd have to go over those again and change all `needs` and `triggers` for `package:foo` to `pkg_apt:foo` or whatever.

**Comment by trehn** [comment]
The current state of things is that we're being as smart as possible based on `node.os` and the new `node.os_version`. But whatever you *can* do in a bundle (like selecting the correct kind of package), you still have to do in a bundle.
