### ISSUE TITLE
Add support for systemctl enabled/disable

### ISSUE THREAD

**Issue by rullmann** [bundlewrap/bundlewrap#199]
When installing a custom service or even programs from EPEL systemctl enable <servicename> is not always triggered.

Currently a definition for such a service would look like this by default:
svc_systemd = {
    'collectd': {
        "running": True,
     },
}

If this feature request would be accepted something like this would be appreciated by default:

svc_systemd = {
    'collectd': {
        "running": True,
        "enabled": False,
     },
}

Thanks! :)

**Comment by vain** [comment]
Funny, I just thought about this topic today.

Yes, we should provide something like this. It’s already covered by this issue, though:

https://github.com/bundlewrap/bundlewrap/issues/137

Also applies to init systems other than systemd.

**Comment by rullmann** [comment]
Well, it has been your Podcast recommendation leading to this thought. Funny.

Very well, I'm fully supporting your issue. Where's the JIRA vote button?
