### ISSUE TITLE
Add support for RedHat DNF

### ISSUE THREAD

**Issue by rullmann** [bundlewrap/bundlewrap#202]
`dnf` will replace `yum` in the future.
Currently using the `yum`-action doesn't result in an error as yum "redirects" to dnf.

`dnf` should be an item in bw in the future.

https://fedoraproject.org/wiki/Features/DNF

**Comment by sq3** [comment]
I started working on this a few weeks ago, but it's currently untested

https://github.com/sq3/bundlewrap/commit/717406cd864e00b7481c7442b120d8c739d4abc1
https://github.com/sq3/bundlewrap/commit/85fc99ca5abc3d059ddd6f87dd4e2f0c39244ddd

**Comment by trehn** [comment]
To me the linked wiki page reads like DNF is slated to be a drop-in replacement for yum and will adopt the yum name once it matures. The `dnf` executable appears to only be a temporary thing until the old yum goes away. If that is the case, I don't see any reason why bw would want to support this. Am I reading that wrong?
