### ISSUE TITLE
Integrated support for Yum

### ISSUE THREAD

**Issue by TechnicalBro** [bundlewrap/bundlewrap#203]
Ive been tinkering with Bundlewrap for a while and love its ease of use; Though the current feature lost only supporrs dpkg/apt-get.. which isnt ideal for my companies setup, as we're mostly a redhat/fedora/centos based host.

Im curious if theres planned support for Yum integration, as currently we're using Fabric and Invoke to create a workaround for this. 

Thanks :)

**Comment by trehn** [comment]
pkg_yum has been in there since 1.3: http://docs.bundlewrap.org/en/1.5.0/item_pkg_yum.html

Is that what you're looking for?
