### ISSUE TITLE
bw 2.0 blockers

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#205]
-   `statedict.py`: `diff_value_list()` is not implemented which breaks all user items (`groups` attribute is a list).
-   `statedict.py`: `diff_value()` does not handle `NoneType` values which also breaks user items because of their optional attributes.
-   User items: `uid` and `gid` attributes of the item are converted to a `str` but the result read from the node is converted to an `int` which makes the assertion in `diff_value()` fail.

**Comment by trehn** [comment]
note to self: get_auto_deps should check for deleted attribute before assigning deps

**Comment by trehn** [comment]
should all be fixed now in master except for `diff_value_list()`
