### ISSUE TITLE
Allow specific versions for APT packages

### ISSUE THREAD

**Issue by timbuchwaldt** [bundlewrap/bundlewrap#228]
In order to pin the package version, one currently has to set it in the pkg_apt items name.
This doesn't work for some packages (As items names can't contain colons, apt package versions can), also other items depending would then need to depend on the specific string. A better option seems to be to introduce an attribute on pkg_apt that specifies a version.

Also: This always tries to re-install the package, as the current matching logic for detecting whether the package is installed fails for packages with a version spec.

**Comment by trehn** [comment]
I really don't want to reinvent the pinning mechanism in APT. https://wiki.debian.org/AptPreferences#Pinning

Why don't you use that?

**Comment by timbuchwaldt** [comment]
Good point, nevermind :) Thx!
