### ISSUE TITLE
Answering "q" to a question does not quit

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#238]
It appears to just skip the item in question.

(I'm almost 100% certain that this worked when I first tested it ... :))

**Comment by trehn** [comment]
It does not quit *immediately*, it allows other threads to complete in an orderly fashion (i.e. finish the apply they're currently doing).

We could make this more immediate by setting a ZOMGQUITNOWASAP `threading.Event`, but then we'd have to check that at several places. Quick win: set the event and only check it in `ask()`, so at least you don't have to answer more questions after answering "q" once.

**Comment by trehn** [comment]
Reading the docs, raising SystemExit in a thread will only quit the thread, not the parent.

Could've sworn it worked at some point. Anyway, the PR should fix that.

**Comment by vain** [comment]
Ah, nice.

I'll have plenty of opportunity to test the PR tomorrow. :-)

**Comment by trehn** [comment]
I only had little time to test this and I have a suspicion: bw quits too promptly after the question has been answered, discarding output that should have been buffered while waiting for the answer. I was unable to create a situation where I would see residual output after answering a question with "q". Though looking at the code, I don't see why that would be the case...

**Comment by trehn** [comment]
Something else I just realized: since ask() holds the output lock while waiting for the answer, it blocks any thread trying to use `io.stdout()` etc.. It would be better if `io.stdout()` et al write to an internal buffer that is flushed once `ask()` releases the lock. I see a dedicated output thread in our future :(
