### ISSUE TITLE
Can BundleWrap reuse SSH connections?

### ISSUE THREAD

**Issue by balone1988** [bundlewrap/bundlewrap#239]
Hey all,

I'm finding BundleWrap fails in my setup whenever I run against multiple nodes at the same time. But since more recent versions (I only just move from 1.5.x to 2.5.x) I find it failing to get through a single node without failing (it seems to persistently fail around the 20th connection to server). I also see that there is a cooling off period of around 30 seconds so where I cannot SSH into our servers. So this is mainly an issue with our setup.

However, just to verify, is BundleWrap reusing SSH connections or is it setting up new ones for every command (I think this is the case).

If it is on every command, is this inefficient? It may certainly be problematic for a firewall we have in place (I've request our IT people look into it too). The giveaway here is the "Connection reset by peer" on both server and client.

Is there a way that BundleWrap could keep the connections alive a use just a small pool rather than making a burst of new connections?

Thanks

**Comment by trehn** [comment]
BundleWrap just invokes `ssh` as you would on the command line. So if you have multiplexing set up in your `.ssh/config`, BundleWrap will use it.

My config looks like this:

```
Host * !github.com
ControlPath ~/.ssh/controlmasters/%r@%h:%p
ControlMaster auto
ControlPersist 10m
```

This will enable multiplexing on all hosts except GitHub. See also:

https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing#Setting_Up_Multiplexing

**Comment by balone1988** [comment]
Thanks for the advice trehn, I've implemented it and it works flawlessly and performs exceptionally well. I simply hadn't come across SSH multiplexing yet.

Could be worth sticking it in the docs too...

Thanks
Tony
