### ISSUE TITLE
Add support for non-Bourne compatible shells

### ISSUE THREAD

**Issue by rullmann** [bundlewrap/bundlewrap#241]
bw will try to set env variables in a Bourne shell compatible way.
Some shells (e.g. fish) don't support this.

Error message:
<pre>
[2016-04-24 18:48:42.774322] bundlewrap: Non-zero return code (127) running 'true' on '192.168.169.30':

Unsupported use of '='. To run 'sudo' with a modified environment, please use 'env LANG=C sudo…'
fish: LANG=C sudo bash -c true
      ^
</pre>

Testing:
<pre>
> env LANG=C sudo bash -c true
> echo $status
0
> LANG=C sudo bash -c true
Unsupported use of '='. To run 'sudo' with a modified environment, please use 'env LANG=C sudo…'
</pre>

It seems like the guys from Ansible had the same issues:
https://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters

**Comment by trehn** [comment]
I think this is more easily fixed by moving `LANG=C` into `-c`:

```diff
diff --git a/bundlewrap/operations.py b/bundlewrap/operations.py
index 12f0b16..1bf3753 100644
--- a/bundlewrap/operations.py
+++ b/bundlewrap/operations.py
@@ -106,7 +106,7 @@ def run(hostname, command, ignore_failure=False, add_host_keys=False, log_functi
             "-o", "PasswordAuthentication=no",
             "-o", "StrictHostKeyChecking=no" if add_host_keys else "StrictHostKeyChecking=yes",
             hostname,
-            "LANG=C sudo bash -c " + quote(command),
+            "sudo bash -c " + quote("LANG=C " + command),
         ],
         stdin=PIPE,
         stderr=stderr_fd_w,
```

This would make it impossible to reliably react to failures in `sudo` or `bash` as requested in #200. But I'm OK with that. I don't think we want to try and be compatible with multiple node shells as Ansible does. That's the whole point of invoking `bash` for everything we do.

@vain any comments?
