### ISSUE TITLE
`bw verify`: Honour `unless`

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#243]
`bw verify` always reports files as unclean even if an `unless` clause holds true.

**Comment by trehn** [comment]
So far, this is intended behavior because there is not guarantee that the `unless` command doesn't change the state of the node. But it's probably better to add a recommendation to the docs regarding the nature of `unless` commands and have them pass a `verify`.

**Comment by vincg** [comment]
I have the same problem, I have attached some information (hope it's enough)

> files = {
>     '/var/named/master/xyz.zone': {
>         'source': 'dns_xyz_base',
>         'owner': 'named',
>         'group': 'named',
>         'mode': '0644',
>         'comment': '(re)create base for dynamic DNS entries for .xyz.zone',
>         'unless': 'test -x /var/named/master/xyz.zone',
>     },
> }

Now `bw verify all` shows this host as bad for the above file having a content_hash mismatch:

> x hostname  bundlename  file:/var/named/master/xyz.zone (content_hash)

**Comment by trehn** [comment]
@vincg You're telling bw to set mode 644 and then test for executable permissions with `-x`. Works for me after fixing that.
