### ISSUE TITLE
persistent locks

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#256]
Here's an idea:

Allow locks not only on the node itself, but also as a node/group attribute. When an entire node is locked this way, `bw apply` doesn't connect at all.

Also add run locking for both this and the on-node soft locks.

This would solve the virtual node problem and also provide people with an SCM-auditable way of temporarily or permanently locking a node. Because reasons.

**Comment by trehn** [comment]
I am not happy with the `bw run` situation. It's necessary to prevent `bw run`s on virtual nodes, but run locking by itself seems clunky. What are the use cases for preventing any command being run on a node? Just denying certain commands (based on a glob pattern or something) feels flaky.

Another thing to consider is abuse of the persistent locks by people too lazy to implement exceptions for certain items in their bundles. Then again maybe a persistent lock is still the most elegant way to express such exceptions.

**Comment by vain** [comment]
I feel that this is just a matter of using the correct words.

If you call it "lock", all the problems you mentioned unfold. Even more: If I was new to this and if I were to read that, say, a network switch is "locked", I'd wonder why that is. To me, "lock" also always implies "temporarily locked". Even a "persistent" lock makes me think, "yeah, this node might get unlocked at some point."

I'd really call it `'connect': False` (as suggested in #186). It's clear what's going on: This is a node that bw does never connect to. Period. No apply, no run, no verify, no nothing.

Users can then use this attribute for whatever reason they might have. Virtual nodes, "temporarily disabled" nodes, ...

Yes, this sacrifices the option of doing a `bw run` on those nodes. IMO, this is a corner case anyway. And, if you really have to, you can still do a `for i in $(bw nodes --hostnames ... | cut -d: -f1); do ssh ...; done`.

**Comment by trehn** [comment]
Going with a simple `node.dummy` for now.
