### ISSUE TITLE
Enable the file items to get a file from a remote location instead of the local repository

### ISSUE THREAD

**Issue by derintendant** [bundlewrap/bundlewrap#275]
I want to be able to use the files directive like that:

```
files = {
    "/opt/confluence/webapps/jolokia.war": {
        "mode": "0644",
        "owner": "confluence",
        "group": "confluence",
        "content_type": "binary",
        "source": "http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war/1.3.4/jolokia-war-1.3.4.war",
    },
}
```

Bundlewrap would check if the source Attribute is a URL and would then download the file to deploy from that location. This way, we can avoid putting (third-party) binary files inside the configuration repository (like the jolokia.war from above).

**Comment by vain** [comment]
I think I like that idea. :-) (Haven't thought about it in depth, but it sounds intriguing.)

Maybe call it `retrieve_binary_from` instead of `source` to avoid that automagic URL detection.

**Comment by trehn** [comment]
Ugh, I don't know. We'd have to implement caching so we don't end up downloading the file 100 times when distributing that file to 100 nodes.

**Comment by vain** [comment]
Possible alternative: Use an `apply_start` hook to download/refresh „remote“ files.

**Comment by rullmann** [comment]
From the docs btw:

> Ansible ships with loads of modules while BundleWrap will only give you the most needed primitives to work with. For example, we will not add an item type for remote downloads because you can easily build that yourself using an action with wget.

http://docs.bundlewrap.org/misc/alternatives/ : Ansible

**Comment by trehn** [comment]
Don't see this happening.
