### ISSUE TITLE
change user in actions

### ISSUE THREAD

**Issue by MaZderMind** [bundlewrap/bundlewrap#292]
> As a bundle-developer I want to be able to run Actions as a different User. I want to be able to specify the user literally or specify a reference-file, as who's owner the command should be executed.

Often Project-Files belong to a specific per-application-user and maintaining this ownership is critical. To accomplish this, management-tools often need to be run as a lower privileged user and can't be ran as root.

Currently this can only be achieved by specifying the command together with a matching `su` call which needs to be constructed in the bundle and carefully quoted:

```
    actions[name] = {
        'command': 'su - wpuser -c "/usr/local/bin/wp \"sth sth\""',
        'needs': ['symlink:/usr/local/bin/wp'],
    }
```

It would be much better to be able to specify the target-user as an option to the action and have the actions-module figuring out the escaping parts:
```
    actions[name] = {
        'user': 'wpuser',
        'command': '/usr/local/bin/wp "sth sth"',
        'needs': ['symlink:/usr/local/bin/wp'],
    }
```

---

Sometimes the name of the user is OS-Specific (unter Vagrant "ubuntu/xenial64"-Image for example al vagrant-files are owned by `ubuntu`). To prevent specifying a special username it would be awsome to be able to specify a reference-file from which the owner is taken as su-user:
```
    actions[name] = {
        'user-reference': '/vagrant/wordpress/htdocs',
        'command': '/usr/local/bin/wp "sth sth"',
        'needs': ['symlink:/usr/local/bin/wp'],
    }
```

We successfully implemented this with the following su-call inside our bundle:
```
su - `stat -c "%U" /vagrant/wordpress/htdocs` -c "/usr/local/bin/wp core config --path=/vagrant/wordpress/htdocs --dbname=wordpress --dbuser=wordpress --dbpass=wordpress"
```

**Comment by trehn** [comment]
Sorry, this is a WONTFIX.

You can get around some of the quoting by using `sudo -u wpuser -- WHATEVER YOU WANT`. I don't see much value in making the user an item attribute, especially since it would require another node attribute similar to `Node.cmd_wrapper_outer`.

`user-reference` is very niche and violates one of the core principles of bw: The node cannot influence the configuration it receives.

**Comment by MaZderMind** [comment]
no reason to apologize. I know how it feels to be a maintainer of some open source software ;)
Thank you for looking into it.
