### ISSUE TITLE
optimize checks for installed packages

### ISSUE THREAD

**Issue by tpenndorf** [bundlewrap/bundlewrap#295]
While running an apply or verify, for every configured packet (deb, rpm), a request to the package management system is run. This is very time consuming.
I would suggest to run one query for all installed packages and compare it with the configured packages. 
Maybe, it should be repeated after every package install, to detect new packages, which were installed as dependencies. 
On nodes with many packages, it would reduce the time roundabout 50%.

**Comment by trehn** [comment]
This has been implemented for APT packages in 0ad7c7303546ff4682e886b23794a412a4bd3e96. Other package item types can take advantage of the common base class introduced in 86f552b4017584b1629f4522d901c0f08fccaa05. Porting them is trivial, but requires testing.

**Comment by trehn** [comment]
We got the important ones covered.
