### ISSUE TITLE
delete user does not work

### ISSUE THREAD

**Issue by bborbe** [bundlewrap/bundlewrap#300]
>     'metadata': {
>        'users': {
>            'admin': {
>                'delete': True,
>            },
>        },

Run "userdel admin" on bash manually does work. 

Using bw 2.12.0 and the target is Raspbian GNU/Linux 8 (jessie)

**Comment by trehn** [comment]
Just setting metadata is not enough to delete a user. What bundle is interpreting that metadata and how? bw does not do anything with metadata by itself.

**Comment by trehn** [comment]
To delete a user, put this in an `items.py`:

```python
users = {
    "admin": {
        'delete': True,
    },
}
```

**Comment by bborbe** [comment]
Ah thx, forgot that ;) Thx
