### ISSUE TITLE
new metadata processor API

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#303]
```python
from bundlewrap.metadata import metadata_processor

@metadata_processor
def myproc(metadata):
    metadata['foo'] = 'bar'
    return metadata, True
```

Returning `True` along with metadata indicates that this processor need not be called again, even if other metadata changes.

Using the decorator removes the need for `from foo import bar as _bar`.

**Comment by trehn** [comment]
returning `True` now available as of ffdb7116c8353a402f0b8791217c324255d46725

**Comment by trehn** [comment]
Here's another idea: metadata processor stages.

In metadata processors, you often see this:

```python
# bundle1/metadata.py

def metaproc(metadata):
    metadata.setdefault('bundle2', {}).setdefault('some_list', [])
    metadata['bundle2']['some_list'].append(1)
```

It's pretty unfortunate that every bundle that uses bundle2 has to duplicate the logic for setting up these defaults. It would be much nicer if bundle2 had a chance to set up it's own defaults and all other bundles could just expect them to already be in place and ready for modification/additions.

One way to solve this is to introduce metadata processor stages. Look at this example:

```python
# bundle1/metadata.py

@metadata_processor(stage=20)
def metaproc(metadata):
    metadata['bundle2']['some_list'].append(1)


# bundle2/metadata.py

@metadata_processor(stage=10)
def metaproc(metadata):
    metadata['bundle2'] = {
        'some_list': [],
    }
```

The stage argument to the metadata_processor decorator is crucial: by choosing a lower stage, this metadata processor is guaranteed to run before any metadata processor in a higher stage. This has a number of advantages:

* It's another way of cutting down on unnecessary reruns of metadata processors. (Currently you can't really safely return `(metadata, True)` as long as you depend in any way on other metadata)
* We lose the setdefault crap and get a nice and clear definition of a default dict for this bundle's metadata.
* bundle1 really only needs to know and do what it must to bundle2's metadata.

One question remains: Is the stage number just a priority that determines the order metadata processors are run? Or are they discrete stages where every metadata processor that shares a stage number is run until none of them return changed metadata?

I think the first variant is probably better, because it's easier to understand (which is quite important with this already advanced topic).

**Comment by vain** [comment]
> Is the stage number just a priority that determines the order metadata processors are run?

Not sure if I understand correctly.

This would mean:

-   Run all metaprocs, ordered by their stage number.
-   Rerun that whole thing until nothing changes anymore.

Right?

**Comment by trehn** [comment]
Right. For this to remain reasible, we either have to a) encourage users to use no more than three well-known priorities or b) provide a means of previewing the order of metadata processors. Otherwise it might become very confusing ordering 100+ metadata processors in your head.

**Comment by trehn** [comment]
Random idea:

```python
@metadata_processor
def myprocA(metadata):
    metadata['foo'] = 'bar'
    return metadata, True, "a"

@metadata_processor(needs=["a"])
def myprocB(metadata):
    metadata['baz'] = metadata['foo']
    return metadata, True
```

**Comment by vain** [comment]
Long story short, explicit dependencies. Yes. I think there's no way around this.

(`"a"` would have to be a list, otherwise it'd be hard to refactor/merge metaprocs. And multiple metaprocs might "provide" `"a"`, so `myprocB` must wait for all of them to finish.)

(Maybe `needs=…` should also be able to select entire bundles.)

Do we really need that `True`? If there are explicit dependencies, we could kick that whole "re-run again until nothing changes anymore" thing. Oh well, maybe in bw 3.0 (or 4.0), since it breaks virtually everything.

**Comment by trehn** [comment]
What if bundles could also just add static dictionaries of metadata that are merged just like group- and node-level metadata?

So

```
def backups(metadata):
    paths = metadata.setdefault('backup', {}).setdefault('paths', set())
    paths.add(‘/var/www’)
    return metadata
```

becomes

```
properties = {
    'metadata': {
        'backup': {
            'paths': set(['/var/www']),
         }
    },
}
```

in `bundle/webserver/bundle.py` or something like that. This would also provide us with a place to put future stuff like bundle dependencies and perhaps bundle-specific tests.

**Comment by trehn** [comment]
Nah, it should live in `metadata.py` as well and co-exist with metadata processors. It should be able to replace all metadata processors that `return metadata, True`:

```python
metadata = {
    'backup': {
        'paths': set(['/var/www']),
    },
}

@metadata_processor
def foo(metadata):
    if metadata['foo']:
        metadata['bar'] = 'baz'
    return metadata
```

**Comment by trehn** [comment]
Oh and here's another idea for metadata processor dependencies. Instead of depending on another *processor*, just depend on a *key* being set:

```python
@metadata_processor(needs=['foo'])
def foo(metadata):
    if metadata['foo']:
        metadata['bar'] = 'baz'
    return metadata
```

Chained decorators for more complex requirements:

```python
@metadata_processor(needs=['foo'])
@metadata_processor(needs=['bar/baz'], allow_none=True)  # {'bar': {'baz': None}}
@metadata_processor(needs=['bar/baz'], required=True)  # raises error if bar/baz never appears, otherwise metaproc just never runs
@metadata_processor(needs_bundles=['iptables'], required=False)  # only run metaproc if iptables bundle is present on node
def foo(metadata):
    [...]
```

**Comment by trehn** [comment]
FTR: needs_key doesn't solve everything because it can't wait on *other nodes* or even request that their metadata be generated.

**Comment by trehn** [comment]
I think it's also a good idea to redesign `return metadata, True`. It's not obvious at all what `True` does here. Instead, we should add some constants to the environment:

```python
def mp1(metadata):
    metadata['foo'] = 1
    return metadata, FINAL


def mp2(metadata):
    return {
        'foo': 1,
    }, FINAL, UPDATE


def mp2(metadata):
    return {
        'foo': 1,
    }, FINAL, DEFAULTS
```

Returning the `FINAL` option will have the same effect as `return metadata, True` has today. Returning the `UPDATE` option will merge the returned dict into metadata (using `bundlewrap.utils.merge_dict`). `DEFAULTS` will do the same thing, but merge metadata into the returned dict instead.

**Comment by trehn** [comment]
I'm also wondering if it'd be worth it to explicitly pass the `node` and `repo` objects to each metadata processor:

```python
def mp3(repo, node, metadata):
     ...
```

That would force users to do this:

```python
def mp4(repo, node, metadata):
    if not node.has_bundle("bundle"):
        return metadata
    else:
        ...
```

Instead of this:

```python
if node.has_bundle("bundle"):
    def mp5(metadata):
        ...
```

It would also allow us to cache metadata processor functions and not have to `exec()` metadata.py for every node (though recent testing has shown this isn't as much overhead as I thought).

**Comment by trehn** [comment]
Another point that has come up repeatedly: Should metaprocs generate as much metadata as possible, without checking if another bundle will actually use it?

One thing I noticed is that in practice overwriting metadata only ever seems to happen at the group/node-level. Metaprocs usually just read something and then create new metadata based on that.

**Comment by trehn** [comment]
We should make returning `FINAL` or `RUN_ME_AGAIN` mandatory. I don't think it would be too much overhead for the user to tell us when they're done. This can save a huge amount of time spent in `deepcopy_metadata()` to figure out if anything changed.
