### ISSUE TITLE
Auto-removal of softlocks broken

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#317]
In `softlock_list()`, we call `softlock_remove()` for expired locks:

https://github.com/bundlewrap/bundlewrap/blob/master/bundlewrap/lock.py#L188

`softlock_remove()` then calls `softlock_list()` again. This can and will lead to an infinite recursion, eventually causing Python to abort.

I wonder why we iterate over all softlocks again in `softlock_remove()`. Why not just try to remove the file? If it exists, we're fine. If it didn't, `return False`. We can use the exit code of `rm` to determine that.

**Comment by trehn** [comment]
brainfart, thx
