### ISSUE TITLE
apt module doesn't seem to  allow me to specify an architecture

### ISSUE THREAD

**Issue by highvoltage** [bundlewrap/bundlewrap#330]
I need to install an i386 package on a multiarch system.

When I specify a package as packagename:i386, then bundlewrap says colons aren't allowed in package names and it doesn't seem to have any other options to specify architecture.

**Comment by trehn** [comment]
Thanks, a fix is included in 2.17.0, which I just released. You will have to replace the colon with an underscore though, e.g.:

```python
pkg_apt = {"libc6_i386": {}}
```

**Comment by highvoltage** [comment]
Perfect, thanks!
