### ISSUE TITLE
how to specify SSH user

### ISSUE THREAD

**Issue by iam404** [bundlewrap/bundlewrap#337]
```
Traceback (most recent call last):
  File "/Users/xyz/PycharmProjects/shelve/controller/bwrapcontroller.py", line 5, in <module>
    uptime = node.run("uptime")
  File "/usr/local/lib/python3.6/site-packages/bundlewrap/node.py", line 685, in run
    operations.run(self.hostname, "true", add_host_keys=add_host_keys)
  File "/usr/local/lib/python3.6/site-packages/bundlewrap/operations.py", line 211, in run
    raise RemoteException(error_msg)
bundlewrap.exceptions.RemoteException: Non-zero return code (255) running 'true' with ID PV9V on 'example.com':

Permission denied (publickey).
```

Sorry If I am asking any basic question . But every time it tries to ssh to any remote system, it takes the user of local and tries to ssh remote system. like if my local user is xyz , it will try to ssh to remote node with "xyz@example.com".

Is their any user option that I can set here:

```
nodes = {
    'node1': {
        'hostname': "example.com",
    },
}
```

**Comment by iam404** [comment]
Also any option to set node localhost. For below option it tries to ssh to localhost.

```
nodes = {
    'node1': {
        'hostname': "127.0.0.1",
    },
}
```

**Comment by trehn** [comment]
You can use your `~/.ssh/config` to do that. Here's how: https://www.digitalocean.com/community/tutorials/how-to-configure-custom-connection-options-for-your-ssh-client#basic-connection-options

I don't understand your second comment. Can you elaborate?

**Comment by iam404** [comment]
ah! `~/.ssh/config` looks good. But any future plan to merge this option inside node.py. Just asking, I do not want to maintain 2 separate files with node list.

My second comment is simple. I want to run command/operations in my local system (not on any remote node).

**Comment by trehn** [comment]
No, we don't want to duplicate features from `~/.ssh/config` in BundleWrap. Note that you can use wildcards in `~/.ssh/config` so you don't have to put each node in there.

If you want to manage your local system, you'll have to do it over SSH. It's too narrow a use case to warrant a special "connection type" that uses local command directly (and I believe it enables bad practices in a team environment).

**Comment by highvoltage** [comment]
I use the following which works fine for me:

```
nodes = {
    'node1': {
        'hostname': "config@example.com",
    },
}
```

**Comment by Shellcat-Zero** [comment]
@trehn The documentation ([quickstart](https://docs.bundlewrap.org/guide/quickstart/)) is a bit deceiving, as it doesn't explain how the username must also be specified for the given hostname.  I thought I had an ssh config problem until discovering @highvoltage's post above.
