### ISSUE TITLE
Bring back default file/dir permissions?

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#358]
Since 4cba7a0, d6f1840, and 678f841, files/dirs/symlinks no longer have a default owner. Before that, the default owner was root. Unfortunately, git history doesn't show *why* this change was made.

I find myself cluttering all kinds of bundles with explicit ownership and permissions:
```
'owner': 'root',
'group': 'root',
'mode': '0644',
```
Virtually every item has those. If another team member *forgets* to set this, we get unpredictable ownership all of a sudden. (This has led to actual bugs where a daemon could not read its files.)

Why did we change the default behaviour to "don't care"? There was probably a good reason to do so. :)

**Comment by trehn** [comment]
Because I felt that not setting an option was the most intuitive way to say "I don't care about this".

If we default ro root:root:0644, "don't care" looks like this:

```python
files = {
    "/etc/something": {
        "owner": None,
        "group": None,
        "mode": None,
    },
}
```

But I guess there are so few situations where you don't care, that bringing back the default is more reasonable.

**Comment by trehn** [comment]
(breaks tests on my machine because macOS doesn't have a root group by default)

**Comment by trehn** [comment]
(I can change the default value to "wheel" on macOS, but then tests still fail because `bw hash` changes)

**Comment by vain** [comment]
> (breaks tests on my machine because macOS doesn't have a root group by default)

It's a GNU-ism, it appears. OpenBSD, NetBSD, FreeBSD, none of them have a root group. :|

**Comment by trehn** [comment]
What do they have? "wheel" like macOS?

**Comment by vain** [comment]
It would appear so:

```
# uname -a
OpenBSD openbsd.my.domain 6.0 GENERIC.MP#2319 amd64
# id
uid=0(root) gid=0(wheel) groups=0(wheel), 2(kmem), 3(sys), 4(tty), 5(operator), 20(staff), 31(guest)
```
```
netbsd# uname -a
NetBSD netbsd 7.0.1 NetBSD 7.0.1 (GENERIC.201605221355Z) amd64
netbsd# id
uid=0(root) gid=0(wheel) groups=0(wheel),2(kmem),3(sys),4(tty),5(operator),20(staff),31(guest)
```
```
root@freebsd:~ # uname -a
FreeBSD freebsd 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
root@freebsd:~ # id
uid=0(root) gid=0(wheel) groups=0(wheel),5(operator)
```
