### ISSUE TITLE
OpenBSD: bw must not try to create users/groups in parallel

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#367]
Yargh.

`nodes.py`:
```python
nodes = {
    'node': {
        'bundles': ['bunch-of-users'],
        'cmd_wrapper_outer': 'sh -c {}',
        'hostname': 'overqemu10',
        'os': 'openbsd',
        'os_version': (6, 1),
    },
}
```

`bunch-of-users/items.py`:
```python
users = {}

for i in range(100):
    users['foobar{}'.format(i)] = {}
```

Result: Some users are created, others are not.

Reason:
```
useradd: can't lock `/etc/master.passwd': Resource temporarily unavailable
```

Worse, this leaves the system in a very weird state:

```
# id foobar6 
uid=1002(foobar6) gid=1002(foobar6) groups=1002(foobar6)
# grep foobar /etc/master.passwd                                                       
foobar9:*:1000:1000::0:0::/home/foobar9:/bin/ksh
foobar0:*:1003:1003::0:0::/home/foobar0:/bin/ksh
# grep foobar /etc/passwd         
foobar9:*:1000:1000::/home/foobar9:/bin/ksh
foobar0:*:1003:1003::/home/foobar0:/bin/ksh
```

So, the user "exists", but it doesn't have an entry in those files? The user also still exists after a reboot and it has been successfully written to `/etc/pwd.db`, apparently:

```
# strings /etc/pwd.db | grep foobar6
foobar6
/home/foobar6
foobar6
/home/foobar6
1foobar6_syspatch
foobar6
/home/foobar6
```

This means that you can't even do multiple runs of `bw apply ...` as a workaround, because bw only reads `/etc/master.passwd` to determine if a user exists. Subsequent calls to `useradd` will fail in a corrupted system.

I can reproduce the corruption/inconsistency by running `for i in $(jot 99); do useradd foobar$i & done`. bw is not the root cause of the corruption here, but that's not the point. It must not try to create users in parallel on OpenBSD due to the lock file.

(I haven't been able to reproduce the inconsistency in OpenBSD 5.9, but there's a lock file as well.)

**Comment by vain** [comment]
Of course, `groupadd` uses a lock file, too.

**Comment by vain** [comment]
Looking at the code in `deps.py`, I don't think there's a simple way to fix this. We would need to turn `BLOCK_CONCURRENT` into an instance attribute which would result in quite some changes to `_inject_concurrency_blockers()`, IIUC. Let's not do this right now as the 3.0 release is imminent.

Maybe just set `BLOCK_CONCURRENT = ["user"]` and the same for groups? That would slow down Linux users, though.

I have a feeling that I'm the only person around who uses bw to manage an OpenBSD node, so I'd be happy to just use `bw apply -P 1` for the time being.

**Comment by trehn** [comment]
I'd rather fix it now. To do this in a backwards-compatible way, we'd have to introduce the `block_concurrent()` class method *in parallel* to the `BLOCK_CONCURRENT` class attribute.
