### ISSUE TITLE
stat fails on OpenBSD

### ISSUE THREAD

**Issue by vincg** [bundlewrap/bundlewrap#380]
**Steps to reproduce:**

1. have a node like the following
`
'host': {
    'hostname': 'hostname',
    'OS': 'openbsd',
    'bundles': (
        'bundle_xy',
    ),
},
`
2. have something in `bundle_xy/files/dhcpd_conf`
3. insert the following into `bundle_xy/items.py`
`
files = {
    '/etc/dhcpd.conf': {
        'source': 'dhcpd_conf',
        'mode': '0644',
    },
}
`

4. run bw apply on the host

error message:
> RemoteException
> Non-zero return code (1) running 'stat -c '%U:%G:%a:%s' -- /etc/dhcpd.conf' on 'host':
> stat: unknown option -- c
> usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]

**note:**
https://man.openbsd.org/stat mentions no option "-c" as well

**Comment by trehn** [comment]
Did you set the 'os' property on the node in question? http://docs.bundlewrap.org/repo/nodes.py/#os

**Comment by vincg** [comment]
Yes, it's set to openbsd

**Comment by trehn** [comment]
'os' should be lowercase

**Comment by vincg** [comment]
I just found the issue. I had the property named 'OS' (uppercase) which apparently bw does not like. Using lowercase makes it work.
