### ISSUE TITLE
Consider storing softlocks under /var/tmp instead of /tmp

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#383]
/tmp is cleared on both Linux and the BSDs during boot. When you lock a node and then reboot it, the lock is lost. I don't think many people have that in mind or even know about it.

On the other hand, /var/tmp will be preserved.

OpenBSD 6.2, though: No effect. /var/tmp is a symlink to /tmp.

**Comment by trehn** [comment]
To do this in a backwards-compatible way, we'd have to write and check both locations until 4.0. Not sure if worth it. Happy to change it with 4.0.

**Comment by vain** [comment]
Yes, +1 for 4.0.
