### ISSUE TITLE
pkg_openbsd - function pkg_installed is broken

### ISSUE THREAD

**Issue by vincg** [bundlewrap/bundlewrap#389]
the regex used in pkg_installed does not work, it fails with
`AttributeError("'NoneType' object has no attribute 'groups'",)`
in `PKGSPEC_REGEX.match(line).groups()`
in `pkg_installed(node, pkgname)`
witch gives a hint that it simple did not match anything and therefor there are no groups

I tried the used regex with regexr.com over my installed packages and it did not work either,
I figured out some problems with the used regex `^([^-]+)-(\d[^-]+)(-(.+))?$`:
1) it does not account for the possibility of '-' in packages names, e.g. "zabbix-agent"
2) if has a problem with flavors being there or missing entirely, e.g. "autossh-1.4e" vs. "cyrus-sasl-2.1.26p17-pgsql"

proposed solution:
1) use a regex to split package name and the rest at the first "-\d", proposed regex: `^(.+)-(\d.+)$`
2) I could not find a suitable regex for the second part, since something being there or missing seems to be a problem with regexes (or maybe I am just not good enough at using them), therefor I would use pythons split and determine on the result length (1 or 2) if we have a flavor in that or not

proposed code to fix this (see below) has been tested with my result of `pkg_info | cut -f 1 -d ' '`
```
PKG_VRS_SPLIT = re.compile(r'^(.+)-(\d.+)$')

def pkg_installed(node, pkgname):
    result = node.run(
        "pkg_info | cut -f 1 -d ' '",
        may_fail=True,
    )
    for line in result.stdout.decode('utf-8').strip().splitlines():
        # There will always be two groups in every line,
        # package_name and version (plus flavor, if there is more than one),
        # where version might contain only the version or additionally the flavor.
        # package_name MAY contain '-', e.g. 'zabbix-agent'

        installed_package, package_info = \
            PKG_VRS_SPLIT.match(line).groups()

        # There can only be one '-' of interest left, in package_info, but it
        # does not have to be there if this package has just one flavor.
        # If we have a flavor, we will have two items after splitting:
        # version and flavor. If not, there will be only one item: version.

        package_info = package_info.split('-')
        installed_version = package_info[0]

        # This either uses the given flavor,
        # or the equivalent to using the "normal" flavor.

        installed_flavor = package_info[1] if len(package_info) == 2 else ""

        if installed_package == pkgname:
            return installed_version, installed_flavor

    return False, None

```

**Comment by vain** [comment]
Oh boy, what a mess.

I think you're right, `split()` is probably the way to go. Let's not cram everything into the regex.

I pushed the `fix-openbsd-package-issues` branch. Could you give it a try?

FYI @trehn That branch contains a bunch of unit tests.

By the way, I found a package called `eagle-1.0-beta39`. Yes, `beta39` appears to be part of the *version*, not a *flavor* (http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/lang/eagle/Makefile?rev=1.21&content-type=text/x-cvsweb-markup). I politely refuse to support this. This is not a sane package name.

**Comment by vain** [comment]
(Given the length of that comment, we probably should add unit tests for the `pkg_install()` mess as well.)

**Comment by vincg** [comment]
Thank you, I will. I´ve been occupied with an entirely different issue for
the rest of today´s workday. I will give it a try tomorrow and let you know
how that works out.

Peter Hofmann <notifications@github.com> schrieb am Do., 15. Feb. 2018 um
17:27 Uhr:

**Comment by vincg** [comment]
Works for me now, thanks! :)
