### ISSUE TITLE
How to pass input to action command prompts?

### ISSUE THREAD

**Issue by Shellcat-Zero** [bundlewrap/bundlewrap#428]
Some commands will prompt for passwords or other inputs, what is the recommended way of passing these when prompted?  I thought that applying the bundle interactively would allow me to enter my credentials manually during the operation but this does not appear to be true.

As a side note, I've traditionally used [Python Keyring](https://github.com/jaraco/keyring) to keep credentials out of source code and pass values as needed.

**Comment by trehn** [comment]
You can pass data through https://docs.bundlewrap.org/items/action/#data_stdin but not interactively.

**Comment by Shellcat-Zero** [comment]
Great, thanks @trehn.
