### ISSUE TITLE
How to build the full BundleWrap repository from the API?

### ISSUE THREAD

**Issue by Shellcat-Zero** [bundlewrap/bundlewrap#430]
The example API usage is:
```python
from bundlewrap.repo import Repository

repo = Repository("/path/to/my/repo")
node = repo.get_node("mynode")
uptime = node.run("uptime")
print(uptime.stdout)
```

but how would you build the repository from the API if it didn't already exist on disk?  My use case is that I need to be able to generate and execute BundleWrap configurations from Python and then optionally save them to disk for future use.  At present, my workaround is to make a bunch writes to file (for the repository) and then often run BundleWrap with `os.system` calls, mostly because there doesn't seem to be any progress/debugging output if using `node.apply` from the API as opposed to using the CLI.  

If this is missing functionality in the API, would you welcome some pull requests relevant to this?  Thanks for all of your work on BundleWrap, it's my favorite configuration management utility.

**Comment by Shellcat-Zero** [comment]
I need to do finer-grained cluster control, and I am working on expanding your API to address the functionality I've mentioned above.

**Comment by trehn** [comment]
This is not possible at the moment. Whenever I tried, at some point it just seemed easier to use files (e.g. for file templates). Supporting all features (think metadata processors, binary files, ...) would be quite an investment.

**Comment by trehn** [comment]
I just don't see this happening without touching the disk.

You might be interested in `bundlewrap.utils.testing.make_repo()` which let's you do this:

```python
from pathlib import Path
from bundlewrap.repo import Repository
from bundlewrap.utils.testing import make_repo


make_repo(
    Path("/tmp/bwrepo"),
    bundles={
        "test": {
            'files': {
                "/foo.txt": {
                    'content_type': 'mako',
                    'content': "${node.name}",
                },
            },
        },
    },
    nodes={
        "localhost": {
            'bundles': ["test"],
        },
    },
)

repo = Repository("/tmp/bwrepo")
```
