### ISSUE TITLE
[RFC] move node attributes into metadata

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#469]
bw itself so far has never used anything in metadata, that was always firmly the user's domain.

If we, however, moved node attributes like `os`, `os_version`, `hostname` into metadata, we could take advantage of the infrastructure available there for computing metadata.

Then we could set `hostname` to whatever metadata logic determines the primary IP address to be, reducing reliance on DNS.

**Comment by vain** [comment]
Sounds like a good idea. (There it is again, a glimpse of the Megadict.)

The only downside that I can see: You’d have to compute full metadata even for simple operations like `bw run`. Which is really slow. Or stuff like `sshn $nodename`. I’m not sure if we can afford this performance impact.

**Comment by trehn** [comment]
How about this: `node.hostname` lazily defaults to `node.metadata['hostname']`. Nothing else changes.

With that, I am also reconsidering the removal of `--adhoc-nodes`.

**Comment by trehn** [comment]
Nah, especially with TOML nodes now, quickly creating a one-off node file is easy enough to leave `--adhoc-nodes` out.

Let's leave metadata untouched.
