### ISSUE TITLE
[RFC] node.metadata_get

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#470]
`node.metadata_get('some/nested/path', 'default')`

as a shortcut (and readability aid) for

`node.metadata.get('some', {}).get('nested', {}).get('path', 'default')`

**Comment by vain** [comment]
Going to be obsolete once Metastacks are rolled out, but :+1: until then.

**Comment by trehn** [comment]
So you want to return a Metastack from `node.metadata`, too? I was not aware of that. Wouldn't it be inconvenient having to provide a default value for `.get()` in items.py?

**Comment by vain** [comment]
You’re right.

I was primarily thinking about having a uniform interface to work with metadata. It’s probably a bit confusing to deal with Metastacks in metadata.py and then dicts in items.py. (Also thinking about something like: “Let’s have a lib that works on metadata. And has unit tests.”) But being forced to provide defaults is meh …
