### ISSUE TITLE
bw diff

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#474]
Helper for finding differences between git branches.

`bw diff`

Runs `bw hash -d`, switches to master branch, runs `bw hash -d` again, `diff -u0` for both results, then switches back to original branch.

`bw diff -m`

Same, but with `bw hash -md`.

`bw diff --to prod`

Use a different branch to diff against.

`bw diff node1`

Diffs `bw hash -d node1` or `bw metadata node1` with `-m`.

**Comment by trehn** [comment]
What are the implications of switching branches? We probably need to ensure no uncommitted changes in git and warn users not to mess with git themselves while this is running. Or can we do independent shallow clones to tmpdirs? Might be complicated by `repo.path` not being the top-level dir for git.

**Comment by trehn** [comment]
Might there also be a use case for just diffing two nodes in the same branch? Should that be a different command? How do we make it clear which is which?

**Comment by trehn** [comment]
Maybe always diff two nodes on the same branch unless `--to` is given.

**Comment by vain** [comment]
(Probably trivial, but it should work with arbitrary commit hashes, too.)

**Comment by trehn** [comment]
I want to put this in 3.10 so it's available to help with metadata processor conversion.
