### ISSUE TITLE
apparently guaranteed determinism is hard

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#481]
```
@metadata_reactor
def one(metadata):
    x = metadata.get('x', []).copy()
    if len(x) < 2:
        x.append(1)
    return {'x': x}

def two(metadata):
    x = metadata.get('x', []).copy()
    if len(x) < 2:
        x.append(2)
    return {'x': x}
```

Depending on execution order, we could end up with `[1, 2]` or `[2, 1]`.

**Comment by trehn** [comment]
one more reason to always treat lists and tuples as atomic (see also #471)

**Comment by trehn** [comment]
But you can run into the same issue with sets:

```
@metadata_reactor
def one(metadata):
    x = metadata.get('x', set()).copy()
    if len(x) < 1:
        x.add(1)
    return {'x': x}

def two(metadata):
    x = metadata.get('x', set()).copy()
    if len(x) < 1:
        x.add(2)
    return {'x': x}
```

Will end up with either `{1}` or `{2}`, depending on exec order.

**Comment by trehn** [comment]
I mean, there is nothing stopping people from calling `randint()` or external data sources. So we can't guarantee determinism. We could either sort reactors to create a defined execution order (and hope people don't rely on it) or deliberately shuffle execution order so people will be more likely to notice they can't rely on it.

**Comment by j-p-a-u-l** [comment]
Maybe testing the meta_reactors with different execution orders could help?

This could lead people direct to this type of problem.

**Comment by vain** [comment]
Okay, the second example (the one with sets) is caused by the two metaprocs disagreeing on the default. In other words, could by solved by #479.

And it’s another reason not to spread defaults all over the place. Need to think more about this … The current state still doesn’t feel like a clean solution. :|

**Comment by trehn** [comment]
Um no, the second example is not solved by #479 since we cannot detect those `.get()` defaults in user code (which don't even have to be passed to `.get()`, as illustrated in the first example).

**Comment by trehn** [comment]
> Maybe testing the meta_reactors with different execution orders could help?

That's what I meant by "deliberately shuffle execution order so people will at least be more likely to notice".

**Comment by vain** [comment]
> Um no, the second example is not solved by #479 since we cannot detect those .get() defaults in user code (which don't even have to be passed to .get(), as illustrated in the first example).

Yes. There were a couple more thoughts pending in my brain that didn’t make it into the comment. Disregard me. Sorry for the noise.

**Comment by vain** [comment]
> That's what I meant by "deliberately shuffle execution order so people will at least be more likely to notice".

Yes. I’m in strong favor of doing that. Shuffle both metaproc order and node order.

**Comment by trehn** [comment]
shuffle PR: #490
