### ISSUE TITLE
Can we throw errors on duplicate metaproc names?

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#483]
We just had two `def foo()` in one `metadata.py`. Can we detect this and throw an error?

**Comment by trehn** [comment]
Maybe, but I smell dragons: https://docs.python.org/3/library/ast.html

**Comment by trehn** [comment]
The low-tech way would be to make use of our decorators somehow.

**Comment by vain** [comment]
Looks like decorators can “see” duplicate functions. `_metadata_defaults_and_reactors()`, which iterates over stuff returned by `exec()`, can not. So, yes, maybe this could be done by some decorator magic.

Will have to investigate if this is *guaranteed* behaviour or if just my Python implementation happens to work this way.

**Comment by trehn** [comment]
Pretty sure that's guaranteed. The second `def` is just changing the contents of the variable that is the function.
