### ISSUE TITLE
Improve/rework "bw test -s"

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#498]
This test is from a time when we expected people to call `vault.password_for()` in `items.py` or even templates. Use of these functions has shifted towards metadata: One bundle or static node metadata calls the function once and then multiple bundles use it.

**Comment by vain** [comment]
Also, this is a separate call of `bw test`, meaning everything has to be tested twice. Takes a lot of time.

**Comment by j-p-a-u-l** [comment]
+1

**Comment by trehn** [comment]
So should we just remove it?

**Comment by vain** [comment]
I would love to keep this test-able, but I don’t see a good way to implement it. :(

Nuke it.
