### ISSUE TITLE
files-item: provide a way to state this file will change on the node

### ISSUE THREAD

**Issue by fkusei** [bundlewrap/bundlewrap#517]
I have an item to deploy a file onto a node, but a later action will modify this file. There should be a way for bw to determine if the to be deployed file is the same file as the original file.

This could be archived by locally generating a hash of that file, also deploying that hash onto the node, and then only change the file if the hash changed.

**Comment by trehn** [comment]
Can't you grep with an action to detect the change? Is *any* change valid?

**Comment by fkusei** [comment]
I have to look into this a bit further. Do some testing and maybe do a PR or something.

**Comment by fkusei** [comment]
Fixed it another (possibly better) way. No need for the action anymore.
