### ISSUE TITLE
Locking: Locks not shown if connection errors occur

### ISSUE THREAD

**Issue by fkusei** [bundlewrap/bundlewrap#519]
When doing a `bw lock show group-with-some-unreachable-nodes`, bw will show the connection errors, but not the lock status of the reachable nodes.

I'd expect bw to output the list of locks, followed by the errors (like what's happening when doing `bw apply group-with-some-unreachable-nodes`).

**Comment by Kunsi** [comment]
I think the problem is in cmdline/lock.py#189 - introduced in 872d7cbe9. Is there a reason why there's an early return in there?

**Comment by trehn** [comment]
I think the only reason is that we throw the results table into a pager if it gets too big. When that's the case, the errors won't be visible at all until the user exits the pager, which might be confusing. Hm...
