### ISSUE TITLE
Feature Request: List of things which should be deployed as early as possible during apply

### ISSUE THREAD

**Issue by fkusei** [bundlewrap/bundlewrap#540]
We get a lot of 'sudo: cannot resolve hostname' emails when doing an initial apply of a node. Some time during an apply, a `/etc/hosts` file gets deployed, which then allows us to resolve the host name of this machine.

Ideal would be to deploy this file as early as possible during an apply, to avoid getting most of those mails.

**Comment by veecue** [comment]
What I do for this is create a tag called "init" (with proper dependencies within the tag) and then deploy a new node using `bw apply node-1 -o tag:init` first

**Comment by fkusei** [comment]
Yeah, using a tag would work - but we're also talking changing node hostnames and stuff. Would like to avoid having to do two applies :/

**Comment by veecue** [comment]
Another possibility I can think of would be adding a global item attribute called `stage` or `priority` or something like that and then have all items of a stage depend on all ones of the previous stage. This could either be numbers (0 would be the default, negative some init stuff and positive some check/test/finalize stuff). Maybe also using texts (`pre-init`, `init`, `finalize`, `post-finalize`), would be less flexible but easier to use. Having a `needs` to a higher stage would have to raise an error in `bw test` then.

**Comment by trehn** [comment]
resolved in #559
