### ISSUE TITLE
Feature Request: `bw diff` should be able to show a diff between local file and node

### ISSUE THREAD

**Issue by fkusei** [bundlewrap/bundlewrap#548]
I just ran `bw verify` against a couple of nodes, which gave me a list of all the things that are not "correct". However, to find out what exactly has changed, i need to run `bw apply -i`.

It would be nice if i could use `bw diff` to just show me the diff between the node and the locally generated version. In my opinion it would be enough to limit this to one file per call.

Maybe this could be the default when calling `bw diff -i file:/some/path -- only-one-node`?

**Comment by ThreeFx** [comment]
Overloading the `diff` command this way might confuse users, maybe adding it to `bw verify` is better instead?

**Comment by Kunsi** [comment]
Sure, adding it to `bw verify` would work, too.
