### ISSUE TITLE
Extra empty lines for output on remote STDERR

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#55]
On current master. This empty line shouldn't be there:

	(virtualenv)$ bw run -f testvm -p 2 'echo hi >&2'
	[overqemu20] err: hi

	[testvm] ✓ completed successfully after 0.191166s
	(virtualenv)$

It's interesting to note that I sometimes get this instead:

	(virtualenv)$ bw run -f testvm -p 2 'echo hi >&2'

	[overqemu20] err: hi
	[testvm] ✓ completed successfully after 0.221963s
	(virtualenv)$

I used `-p 2` simply to trigger `interactive = False`. It doesn't matter if there's one or two workers.

So far, I narrowed it down to `combine_stderr`. If it's effectively False (remember, for `pty = True`, `combine_stderr` has no effect), then I can see the bug. Appears to be something deeper inside Fabric. LineBuffer doesn't appear to be the cause.

I labeled it as "easy" because it's a very minor bug. I guess, this won't be easy to fix, though.

(We stumbled upon something similar in #10. However, that empty line wasn't there.)

**Comment by trehn** [comment]
This is now fixed as a side effect of #144.

```
> bw run -f test -p 2 'echo hi >&2'
[test] hi
[test] ✓ completed successfully after 1.640049s
```
