### ISSUE TITLE
`less -FR` doesn't work as expected on macOS

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#551]
quits without printing anything

**Comment by MaZderMind** [comment]
Workaround: `brew install less` bringt ein Linux-Komptabiles Less, das kann dann auch -FR

**Comment by vain** [comment]
Maybe we should just remove `-F`. It has the potential for endless debates: It’s annoying for users who don’t like it, but others might insist on having it. I suggest that users who do want to have it it set it in their `$LESS`.

**Comment by vain** [comment]
btw, I see the same bug on OpenBSD. It’s really stupid. I ran `ktrace` and saw this: `less` switches to the secondary terminal buffer (`\e[?1049h`), prints the output from the pipe, and then switches back to the primary buffer (`\e[?1049l`). Well done, no output visible.
