### ISSUE TITLE
Stages

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#553]
Stages introduce a new type of configurable dummy item:

```python
# items.py

stages = {
    'my_first_stage': {
    },
    'my_second_stage': {
        'needs': ['stage:my_first_stage'],
    },
}

files = {
    '/foo-1': {
        'stage': 'my_first_stage',
    },
    '/foo-2': {
        'stage': 'my_first_stage',
    },
}

actions = {
    'compress': {
        'command': 'gzip /foo-*'
        'stage': 'my_second_stage',
    },
}
```

Stages only allow the `needs`, `needed_by`, and `tags` item attributes. They work like 'item groups' and will add those values to the respective ones set on each item in a stage. Internal dummy items (`bundle:*`, `tag:*`, ...) are never part of any stage.

BundleWrap creates three stages by default: first, default, last. All items default to the 'default' stage. All user-defined stages and the 'default' stage get an implicit dependency on 'first'. 'last' gets an implicit dependency on all user-defined stages and the default stage.

Stages other than `default` will log a message during `bw apply` when they start and end (as long as they have items).

**Comment by trehn** [comment]
I'm also considering some internal refactoring to get rid of DummyItems. All these subclasses are really just ways to address groups of items. Having them as items in the dependency tree was just a hack that seemed easy before `needed_by` and such came around.

Since stages really are just another kind of item group, I don't really want them in `items.py`. This is also evident in that they wouldn't take all the attributes regular items understand. So maybe this is actually the time to finally introduce a `bundle.py` where we can define stages and perhaps other things in the future.

**Comment by veecue** [comment]
This seems to be a much more mature concept that what I came up with. And always +1 from my side for allowing more metaprogramming :) (I LOVE metadata reactors already)

**Comment by trehn** [comment]
As of #559, stages can now be realized through tags and the new bundle.py:

```python
# bundle.py next to items.py
tags = {
    'before-everything-else': {
        'needed_by': {'tag:', '!tag:'},  # all items with *other* tags and all untagged items
    },
    'normal-stage-1': {},
    'normal-stage-2': {
        'needs': {'tag:normal-stage-1'},
    },
    'normal-stage-3': {
        'needs': {'tag:normal-stage-2'},
    },
    'after-everything-else': {
        'needs': {'tag:', '!tag:'},  # all items with *other* tags and all untagged items
    },
}
```

**Comment by veecue** [comment]
Thanks for the implementation.
I tried using this today and found this code to be working (your exact examples creates a dependency loop error):
```python
# bundle.py next to items.py
tags = {
    'before-everything-else': {
        'needed_by': {'!tag:before-everything-else'},  # all items without this tag
    },
    'normal-stage-1': {},
    'normal-stage-2': {
        'needs': {'tag:normal-stage-1'},
    },
    'normal-stage-3': {
        'needs': {'tag:normal-stage-2'},
    },
    'after-everything-else': {
        'needs': {'!tag:after-everything-else'},  # all items without this tag
    },
}
```
Thanks to tag inheritance, I can also split the before-everything-else into multiple stages (this is, what I currently use):
```python
tags = {
    # Everything that should be done before all normal steps
    'pre-all': {
        'needed_by': {'!tag:pre-all'},  # all items without this tag
    },
    'init': {
        'tags': {'pre-all'},
        'needed_by': {'tag:update-system'},
    },
    'update-system': {
        'tags': {'pre-all'},
    },

    # Everything that should be done after all normal steps
    'post-all': {
        'needs': {'!tag:post-all'},  # all items without this tag
    },
}
```
But now I get almost everything cascade skipped if anything in pre-all is skipped, which happens a lot, either because of 'unless' or because of interactive skipping/commandline skipping, almost all my items are skipped. Therefore I would need some way to disable cascade skipping for dependencies set for tags.

**Comment by veecue** [comment]
@trehn Can you reopen this for now?

**Comment by trehn** [comment]
should be good now with #609
