### ISSUE TITLE
RFC: disabled items

### ISSUE THREAD

**Issue by CroneKorkN** [bundlewrap/bundlewrap#608]
Currently, if we want to controll, whether or not an item should be performed, we put it in a conditional:
```python
if node.metadata.get('do_it', False):
  actions['some_action'] = {}
```

The Problem: this punches a hole in the dependency chain. The code to deal with this can become very confusing:
```python
actions['first'] = {
}
if node.metadata.get('do_second', False):
  actions['second'] = {
    'needs': [
      'actions:first',
    ],
    'needed_by': [
      'actions:last',
    ],
  }
if node.metadata.get('do_third', False):
  actions['third'] = {
    'needs': [
      'actions:first',
      *(['actions:second'] if node.metadata.get('do_second', False) else []),
    ],
    'needed_by': [
      'actions:last',
    ],
  }
actions['last'] = {
    'needs': [
      'actions:first',
    ],
}
```

The solution: decoupling the dependency chain from the decision, whether an item should be performed ot not. Instead if completely removing the item, we could simply disable it:
```python
actions['first'] = {
}
actions['second'] = {
  'enabled': node.metadata.get('do_second', False),
  'needs': [
    'actions:first',
  ],
}
actions['third'] = {
  'enabled': node.metadata.get('do_third', False),
  'needs': [
    'actions:second',
  ],
}
actions['last'] = {
  'needs': [
    'actions:third',
  ],
}
```

**Comment by trehn** [comment]
`'enabled'` clashes with `svc_systemd`, at the very least it must be called something else

**Comment by trehn** [comment]
My first thought was that it would be kind of cool for `unless` to accept a boolean. But that gets in the way if you want to disable an items that has a real `unless` condition.

So I propose a new attribute called `skip`. It will also make `cascade_skip` default to `False` (until we get rid of that and introduce `after`).
