### ISSUE TITLE
Unclear how to configure localhost

### ISSUE THREAD

**Issue by usrme** [bundlewrap/bundlewrap#616]
I've recently just started looking into using Bundlewrap and the example on the homepage lead me to believe I could easily start configuring my personal machine, but on executing the very last command displayed there I ran into an error:

```console
$ bw apply -i localhost
i localhost  started at 2021-03-17 16:20:09
! localhost  Connection error: Non-zero return code (255) running 'true' on 'localhost':

usrme@localhost: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).



i localhost  completed after 0s  (0 OK, 0 fixed, 0 skipped, 0 failed)

!!! There was an error, repeated below.

! localhost  Connection error (details above)
```

Is there a way I should configure my machine that doesn't involve setting it up to allow SSH or if it does require that, would you be able to tell what the bare minimum steps are to do so? I searched the documentation for "localhost", but came up short on how to run anything against the same machine where the configuration code itself lives.

**Comment by trehn** [comment]
BundleWrap will always use SSH, there is nothing special about localhost in that regard.

You need to get your system to a point where `ssh localhost sudo id` will work without prompting you for a password. You already have a server running, so it may be as simple as `cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys` and adding `usrme ALL=(ALL) NOPASSWD: ALL` to `/etc/sudoers`.

**Comment by usrme** [comment]
Thanks for the help! I've got it working now.

Are you open to a PR to add this bit of information to the documentation? I was thinking that the quickstart page would be a good place for something like this.

**Comment by trehn** [comment]
Sure!
