### ISSUE TITLE
Error on duplicate items

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#626]
This should raise an error:

```
$ cat bundles/a/items.py 
files['/etc'] = {'content': 'x'}

$ cat bundles/b/items.py 
files['/etc'] = {'content': 'y'}

$ bw test node-1
✓ No reactors violated their declared keys
✓ node-1  has no metadata conflicts
✓ node-1  b  file:/etc

$ bw test node-1
✓ No reactors violated their declared keys
✓ node-1  has no metadata conflicts
✓ node-1  a  file:/etc

$ bw items node-1
file:/etc
file:/etc
```

I vaguely remember people asking for this to be fine *if* the items are identical … ? Or something like that?

**Comment by fkusei** [comment]
Maybe we should also show which node the error is in?

**Comment by ThreeFx** [comment]
For the record I ran into this and think that it should be allowed iff the items are identical.

Case in point: I have multiple bundles which share a directory. Each bundle needs to create the directory if needed, and so they all had a corresponding directory item until I ran into this issue.

It can be simulated by using metadata to pass around bundle information, but that feels hacky.
