### ISSUE TITLE
Should node.upload retain the permissions of the target file if it exists?

### ISSUE THREAD

**Issue by ThreeFx** [bundlewrap/bundlewrap#628]
Currently I'm writing code for a new item which is something of a smart file manager (think of it as managing a handfull of files and having a more sophisticated replacement logic than "if different then update").

I'm using an auto dependency on all paths I'm managing: Each path must have a corresponding `file` definition. Idea here is that I'm not duplicating the file definition logic.

Now the problem arises when I want to use `node.upload` to upload the content into the (now correctly owned and permissioned) files. `mv` overwrites ownership (well not technically, it simply deletes the destination if it ever existed, but the effect is identical).

`cp` does not overwrite permissions by default. My question is whether it would make sense to change the semantic of `node.upload` to use `cp` followed by `rm` instead of `mv`.

Pros:
  * existing permissions are retained if the file exists

Cons
  * temporarily duplicates the used space

**Comment by vain** [comment]
I’m not 100% sure what you’re trying to do, but I agree that we should replace `mv` by `cp + rm`, because I think this is actually a bug. Here’s why:

Suppose a user does this:

```
files = {
    '/tmp/bla': {
        'content': 'hi\n',
        'owner': None,
        'group': None,
        'mode': None,
    },
}
```

It’s a philosophical question now how to interpret this. Is the intention of the user “I don’t care who owns this file” or is it “please do not change ownership, just manage the content”? Our docs say this for all three attributes:

```
owner

Username of the file's owner. Defaults to 'root'. Set to
None if you don't want BundleWrap to change whatever
is set on the node.
```

But as @ThreeFx noted, we *do* change ownership. bw’s implementation is “I don’t care, I just won’t run `chmod`”, but that’s not enough, since `mv` clobbers permissions.

**Comment by trehn** [comment]
The docs are definitely wrong here, but I think I disagree with the use of `cp` over `mv`.

The general expectation I guess is that BundleWrap will "edit" the content of the remote file, while leaving everything else as is. This is not realistic as we cannot actually open the file for writing like a local one. `cp` will also create a new file and kill the old one, it just happens to have a feature to restore permissions. But permissions aren't even the only relevant thing here. What about timestamps? Extended attributes? ACLs? Even with `--preserve=all`, it's not perfect. Ext4 has a birth timestamp (which would be nice to preserve, right?), but `cp` doesn't know about that yet and will [apparently only deal with atime and mtime](https://github.com/coreutils/coreutils/blob/master/src/cp.c#L302) when you tell it to preserve timestamps.

So, I'd rather be upfront about it: when content changes, `bw` will replace the entire file and clobber ownership, permissions, timestamps, xattrs, and whatever else filesystems may come up with. But we can be explicit about things we'll fix afterwards. We already collect ownership information from the existing file in `sdict()`, nothing wrong with doing a `chown` and `chmod` to restore the previous state before we `mv`. I do like the atomicity of `mv` over `cp`.

**Comment by trehn** [comment]
Now that I said we can't open the file for writing... maybe `cat /tmp/foo.conf > /etc/foo.conf` is a better way to replace just the contents? But then we lose atomicity again.

**Comment by ThreeFx** [comment]
> So, I'd rather be upfront about it: when content changes, bw will replace the entire file and clobber ownership, permissions, timestamps, xattrs, and whatever else filesystems may come up with.

I'd be fine with that as well.

I'll adjust my PR in the coming days to change the documentation instead.

> Now that I said we can't open the file for writing... maybe `cat /tmp/foo.conf > /etc/foo.conf` is a better way to replace just the contents? But then we lose atomicity again.

Ah, this is a great idea, at least for my specific usecase. Hadn't thought of that, thanks!

**Comment by vain** [comment]
Oof. This is one of those “harder than expected” issues. I hadn’t considered atomicity in my comment above. 

I get the impression that atomicity and retaining file modes are mutually exclusive. I played with a couple of scenarios, but I couldn’t get both. :(

When given the choice, I’d clearly go with atomicity.

By the way: We wouldn’t get atomicity with `cp`: `cp` opens both files, then does `read() + write()` in a loop (according to strace). Worse, this is true for `mv` as well, *if* you’re moving between two different file systems (which is not unlikely, btw, bw copies files to `$HOME` first, which might very well be on a different fs than, say, `/etc`, let alone something like `/var/www`). In other words, *we could never guarantee atomicity anyway*.

So how about this:

-   Decide that atomicity (i.e., avoiding partially written files if an SSH connection breaks or if an admin spams ^C) is a must-have.
-   Add a second `mv`, like this:
    ```
    scp localfile node:/home/oink/randomfilename && \
    sudo chown this_and_that /home/oink/randomfilename && \
    sudo mv /home/oink/randomfilename /etc/.passwd.new && \
    sudo mv /etc/.passwd.new /etc/passwd
    ```
    The first `mv` makes sure that we’re on the same file system, so that the second one is atomic.
-   Remove any promises about retaining file modes from the docs/API.

(There is a potential attack in there. It already exists in current bw. What if something writes to `/home/oink/randomfilename` after we’re done writing it and before we move it? Do we have to talk about this or do we ignore it? You can come up with arguments like “if you can do that, you could just run sudo directly”. Dunno. Maybe that’s not always true, maybe there are corner cases we didn’t think about …)

**Comment by ThreeFx** [comment]
> This is one of those “harder than expected” issues.

Agreed :)

Right, atomicity between filesystems is impossible. I agree it would be nice to have it when both are on the same filesystem though.

Re your solution: I don't like that we clobber the target namespace twice with a hidden file. Since the first `mv` is (potentially) non-atomic, a guarantee that the second one is atomic is worthless. If the upload-dest and mv-dest live on different filesystems we can't guarantee atomicity anyway, I think.

random side question: Why does bundlewrap use `$HOME` instead of `/tmp/`?

**Comment by ThreeFx** [comment]
Torsten made good points about the BundleWrap behaviour. We can never guarantee atomicity anyway, and most of this only matters for the initial upload or when using the bundlewrap-internal `node.upload`. I've added a few notes to the docs in #645 which should address the problems I had.
