### ISSUE TITLE
IRC?

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#630]
After [the recent events](https://en.wikipedia.org/wiki/Freenode#Ownership_change_and_conflict) around Freenode, lots of communities moved from [Freenode](https://freenode.net) to [Libera.Chat](https://libera.chat). That wikipedia article lists Vim, RepRap, CentOS, cURL, and Ubuntu. [Wikimedia itself is migrating](https://meta.wikimedia.org/wiki/IRC/Migrating_to_Libera_Chat), too, as are some smaller communities like [Nixers](https://nixers.net/Thread-IRC--1876?pid=22845#pid22845).

Personally speaking, `#bundlewrap` is the last channel that keeps me on Freenode. That’s my main motivation for opening this discussion.

I went ahead and registered `#bundlewrap` on Libera soon after it launched. So, either way, there’s no rush, nobody will “steal” the channel from us. And there are lots of big IRC networks anyway.

*However*, none of us is particularly active on IRC anyway. Do we even *want* to provide “support” on IRC? Do we have the time and energy to do that? Every now and then, someone pops up in the channel, asks a question, but doesn’t get a reply, because we’re all busy. Is it a good idea to announce an IRC channel under those circumstances?

So, again, personally speaking, I’d be happy with one of these options:

1.  Move to Libera. Simply because everyone else is doing it.
2.  Remove references to IRC from our docs. All discussions and “support requests” should be directed towards GitHub issues.

Whaddayathink?

**Comment by Kunsi** [comment]
I'd vote for 1, because I think there should be a difference betwenn "opening an issue because something is wrong" and "i need help because i'm stuck somewhere".

**Comment by vain** [comment]
Alright, given the overall drama and childishness (is that a word?) around freenode, let’s just get this over with, shall we?

![fn](https://user-images.githubusercontent.com/82671/119665824-0d437180-be35-11eb-97cf-4ce15eca457f.png)

I’ll open a PR to change the docs.
