### ISSUE TITLE
Add a short-hand for retrieving passwords?

### ISSUE THREAD

**Issue by ThreeFx** [bundlewrap/bundlewrap#646]
Printing passwords with `bw debug` works, but is unwieldy and I kinda depend on my shell history being long enough.

Having a nicer shorthand for this would be cool, such as `bw pw` or `bw password`.

**Comment by fkusei** [comment]
What's a "password"? In my repository i have [a small script to print all faults in metadata](https://git.franzi.business/kunsi/bundlewrap/src/branch/main/scripts/passwords-for) - but I don't know if that's your definition of a password (since this could also include some cookie secrets and stuff).

**Comment by ThreeFx** [comment]
I specifically mean bundlewrap generated passwords using `password_for` and `human_password_for`. Then the invocation could look like

```
bw pass 'root on example.com'
bw pass --human 'root on example.com'
```
