### ISSUE TITLE
License incompatibility between GPLv2-only (librouteros) and bundlewrap (GPLv3)

### ISSUE THREAD

**Issue by GNUtoo** [bundlewrap/bundlewrap#709]
Hi,

Bundlewrap uses the librouteros library.  The only statement about a license in librouteros proper is in the setup.py[1] where the license is indicated as "GNU General Public License v2 (GPLv2)". 

Since the GPLv2 is incompatible with the GPLv3, I've asked librouterOS if their code was available under the GPLv2-or-later license or if it was GPLv2-only, and unfortunately it's under GPLv2-only[2].

And unfortunately the GPLv2 is incompatible with the GPLv3.

As I understand all the Bundlewrap copyright is owned by the same entity[3], so a way to fix the problem would be to relicense bundlewrap to GPLv3 with an additional permission to link bundlewrap to GPLv2 libraries.

By the way, what is the exact license of what is in the bundlewrap git? Is it GPLv3-or-later? or is it GPLv3-only?

References:
----------------
[1]https://github.com/luqasz/librouteros/blob/master/setup.py
[2]https://github.com/luqasz/librouteros/issues/129
[3]https://github.com/bundlewrap/bundlewrap/blob/main/CAA.md

Denis.

**Comment by GNUtoo** [comment]
> Hi  
Hi,

> GPLv2 only.  
Thanks a lot for the clarification.

PS: I've tried to reply to the bug report by mail but apparently this didn't work.

Denis.

**Comment by emixa-d** [comment]
> Hm. Are you sure it's possible for me to "allow" BundleWrap to be linked against GPLv2 libs? Wouldn't that require the permission of the lib, rather than BundleWrap? My understanding is the only way to do that would be to relicense BundleWrap as "GPL-2.0-or-later".

Maybe you could license BundleWrap as "GPL-2.0 OR GPL-3.0", with the idea that the GPL-3.0 is useless for now (because of the librouteos), so for now people can only effectively use the GPL-2.0 license, but if eventually(?) the librouteos people decide to license it as GPL-3.0, then BundleWrap can be used under the GPL-3.0. I wouldn't know if this holds up legally though.

**Comment by emixa-d** [comment]
> Here is a list of all commands invoked by BundleWrap on managed nodes (though that being relevant to packaging is probably a misunderstanding): https://docs.bundlewrap.org/guide/installation/#requirements-for-managed-systems

Looks like "stat" is run on the remote computer and hence shouldn't be replaced, but "hg/git/bzr/less" is run locally and hence can be replaced? Though for closure size concerns maybe hg/git/bzr should be left as-is.

**Comment by trehn** [comment]
closing this since the author of librouteros doesn't mind and it appears to be GPLv3-licensable anyway as per https://github.com/luqasz/librouteros/issues/129#issuecomment-1136123888
