### ISSUE TITLE
`unless` + `FaultUnavailable` = item not skipped

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#716]
Consider this bundle:
```python
from bundlewrap.exceptions import FaultUnavailable
from bundlewrap.utils import Fault


def _make_fault():
    raise FaultUnavailable


foo = Fault('foo', _make_fault)

files['/tmp/uses-unless'] = {
    'content': '${foo}',
    'content_type': 'mako',
    'context': {
        'foo': foo,
    },
    'unless': 'whatever',
}
```
There’s an `unless` condition and the item also raises `FaultUnavailable` when rendered. I would expect this item to be skipped, but instead I get a long stack trace complaining about `FaultUnavailable`. If you remove the `unless`, it works as expected.

In `items/__init__.py`, not all calls to `cached_status()` are guarded by `except FaultUnavailable`. There is this:

https://github.com/bundlewrap/bundlewrap/blob/7f993eb2dbbe7bbfbfb8f933db71cd3a6e7844a5/bundlewrap/items/__init__.py#L528

`cached_unless_result()` calls `self.cached_status.correct` which raises an uncaught `FaultUnavailable`.

Then there’s also this a few lines further up:

https://github.com/bundlewrap/bundlewrap/blob/7f993eb2dbbe7bbfbfb8f933db71cd3a6e7844a5/bundlewrap/items/__init__.py#L488

Items that precede `file:/tmp/uses-unless` can also trigger `cached_status()` without catching the exception. To reproduce, extend the bundle above with this:
```python
files['/tmp/precedes'] = {
    'content': 'yes',
    'precedes': {'file:/tmp/uses-unless'},
    'triggered': True,
}
```
(To actually see this second bug in action, I commented the entire `elif` in line 528.)

**Comment by vain** [comment]
I don’t really understand why `cached_unless_result()` checks `not self.cached_status.correct`. Can’t we run the `unless` command and, if it’s `true`, then skip the item?

**Comment by trehn** [comment]
Because "unless" is a mechanism to skip fixing an item **if it's broken**. If the item were okay, there would be no reason to call "unless". BundleWrap assumes the item will be okay more often than not. If we called "unless" first and *then* checked if the item is okay, we'd be wasting that first call.
