### ISSUE TITLE
Should `bw test` actually download files?

### ISSUE THREAD

**Issue by zakx** [bundlewrap/bundlewrap#749]
While working on #748, I was wondering about `bw test`. The current behaviour is that `bw test` will actually download files that are defined in bundles as `"content_type": "download"`. This might make sense if the user provides a hash to compare against, but likely makes no sense at all if they don't, instead wasting time and bandwidth.

**Comment by zakx** [comment]
Yeah, but what about cases where the user hasn't set `content_hash`?

**Comment by vain** [comment]
As kunsi said, even if no `content_hash` is provided, a `bw test` should check if the URL actually exist. Or am I missing your point?

**Comment by zakx** [comment]
Checking if the URL exists could be done with a `HTTP HEAD` request though, instead of actually downloading the file.

My original issue is that I have a CI job that runs `bw test` on a repo and that will result in several large downloads, that are useless (beyond checking if the URL exists), because I do not use `content_hash` and therefore downloading the file provides no benefit.
