### ISSUE TITLE
Method 'preview' is abstract in class 'Item' but is not overridden in child class 'Directory'

### ISSUE THREAD

**Issue by MaZderMind** [bundlewrap/bundlewrap#788]
As reported by deepsource:

https://app.deepsource.com/gh/bundlewrap/bundlewrap/run/cc1d80a0-9aad-4ac2-8617-d264cf825faa/python/PYL-W0223?listindex=0

**Comment by vain** [comment]
That’s part of this issue: https://github.com/bundlewrap/bundlewrap/issues/784

(There are several hundreds of DeepSource complaints, it’s probably not viable keeping a GitHub issue for each one of them.)
